# Generated by Django 4.2.9 on 2024-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="admin_command_prefix",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="admin_ids",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="blacklist_ids",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="classroom_group_id",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="classroom_group_id_test",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="google_credentials",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="public_url",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="public_url_test",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="reminders_api_classroom_id",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="reminders_key",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="token_pickle_base64",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="whatsapp_client_url",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="whatsapp_client_url_test",
            field=models.TextField(default="", null=True),
        ),
    ]
