# Generated by Django 5.0.3 on 2024-05-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
