# Generated by Django 4.2.9 on 2024-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_settings_admin_command_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="reminders_api_classroom_id_test",
            field=models.TextField(default="", null=True),
        ),
    ]
