# Generated by Django 4.2.9 on 2024-05-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_ids", models.TextField()),
                ("whatsapp_client_url", models.TextField()),
                ("public_url", models.TextField()),
                ("blacklist_ids", models.TextField()),
                ("admin_command_prefix", models.TextField()),
                ("classroom_group_id", models.TextField()),
                ("reminders_api_classroom_id", models.TextField()),
                ("reminders_key", models.TextField()),
                ("token_pickle_base64", models.TextField()),
                ("google_credentials", models.TextField()),
            ],
        ),
    ]
