# Generated by Django 4.2.9 on 2024-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_settings_reminders_api_classroom_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="ocr_space_api_key",
            field=models.TextField(default="", null=True),
        ),
    ]
