# Generated by Django 4.2.9 on 2024-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_settings_ocr_space_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="openai_api_key",
            field=models.TextField(default="", null=True),
        ),
    ]
