# Generated by Django 4.2.9 on 2024-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_settings_kharchey_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kharchey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.TextField(default="", null=True)),
                ("quantity", models.IntegerField(default=0, null=True)),
                ("price", models.IntegerField(default=0, null=True)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("group", models.TextField(default="", null=True)),
                ("sender", models.TextField(default="", null=True)),
                ("payed", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
