# Generated by Django 4.2.9 on 2024-06-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_kharchey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kharchey",
            name="payed",
        ),
    ]
