# Generated by Django 4.2.9 on 2024-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_kharchey_payed"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(default="", null=True)),
                ("response", models.TextField(default="", null=True)),
                ("group", models.TextField(default="", null=True)),
                ("sender", models.TextField(default="", null=True)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
