# Generated by Django 4.2.9 on 2024-06-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_gptresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="reminders_api_remind_id",
            field=models.TextField(default="", null=True),
        ),
    ]
