# Generated by Django 4.2.9 on 2024-09-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_users_alter_gptresponse_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="google_credentials",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="token_pickle_base64",
        ),
        migrations.AddField(
            model_name="settings",
            name="google_creds",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="utils_server_password",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="utils_server_url",
            field=models.TextField(default=None, null=True),
        ),
    ]
