# Generated by Django 4.2.9 on 2024-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_google_creds_settings_token_pickle_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_outgoing_message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_outgoing_message_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
